version: '3.8'

services:
  asisten-keuangan-app:
    build:
      context: .
      dockerfile: Dockerfile
      # Next.js requires NEXT_PUBLIC_ variables during the BUILD step to inject them into the frontend code
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: asisten-keuangan-app
    restart: always
    ports:
      - "3004:3000"
    environment:
      # Private Keys (Backend Only)
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - XENDIT_SECRET_KEY=${XENDIT_SECRET_KEY}
      - XENDIT_WEBHOOK_TOKEN=${XENDIT_WEBHOOK_TOKEN}
      
      # Public Keys (Usually already injected at build time, but good to have)
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      
      # App Config
      - NODE_ENV=production

  akum_nginx:
    image: nginx:1.25-alpine
    container_name: akum_nginx
    environment:
      - VIRTUAL_HOST=akum.meambo.id
      - LETSENCRYPT_HOST=akum.meambo.id
      - VIRTUAL_PORT=3000
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - proxy_network
    depends_on:
      - asisten-keuangan-app


networks:
  proxy_network:
    external: true